### ISSUE TITLE
SF Pro font?

### ISSUE THREAD

**Issue by ryansereno** [mvritz/dotfiles#1]
Great work on the sketchybar config
Can you tell me where you got the patched SF Pro font?
I tried using a few different patched fonts, but non seem to be rendering the icons in the bar

**Comment by mvritz** [comment]
Thank you!
Will upload the font to the repo later!

**Comment by ryansereno** [comment]
For anyone looking for a solution, I installed Apple's SF Symbols library
https://developer.apple.com/sf-symbols/
